resources:
  - ../../base
  - ingress.yaml
  - sealed-secret.yaml
patchesStrategicMerge:
- replica-count.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernetes-demo-dev
