resources:
- ../../base
- ingress.yaml
- sealed-secret.yaml
patchesStrategicMerge:
- replica-count.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernetes-demo-dev
images:
- name: example-image
  newName: valonjanuzaj/kubernetes-demo
  newTag: 756988a601e5ba56b2d32bfbff90363a8ea2c869
