resources:
- ../../base
- ingress.yaml
- sealed-secret.yaml
patchesStrategicMerge:
- replica-count.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubernetes-demo-dev
images:
- name: example-image
  newName: valonjanuzaj/kubernetes-demo
  newTag: 6c98d59ca668c81305bbbe9fe3a597894f644465
